// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDQW8Eda18PoRmwrMv3SkndxLvtY8qhW-Y',
    appId: '1:254944558379:web:ca243fbb1afc8c5b3fd96e',
    messagingSenderId: '254944558379',
    projectId: 'jejom-d5d61',
    authDomain: 'jejom-d5d61.firebaseapp.com',
    storageBucket: 'jejom-d5d61.appspot.com',
    measurementId: 'G-4E78KXKD7Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAqVytjcDW7phcU6pktGJIgx3cra4iZrs0',
    appId: '1:254944558379:android:ca9e10cd4b5abe753fd96e',
    messagingSenderId: '254944558379',
    projectId: 'jejom-d5d61',
    storageBucket: 'jejom-d5d61.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBQE2XuqnJ7PzTOGFEu936eUjJUdXzo6UA',
    appId: '1:254944558379:ios:59e60474c52b167f3fd96e',
    messagingSenderId: '254944558379',
    projectId: 'jejom-d5d61',
    storageBucket: 'jejom-d5d61.appspot.com',
    iosBundleId: 'com.example.jejom',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBQE2XuqnJ7PzTOGFEu936eUjJUdXzo6UA',
    appId: '1:254944558379:ios:59e60474c52b167f3fd96e',
    messagingSenderId: '254944558379',
    projectId: 'jejom-d5d61',
    storageBucket: 'jejom-d5d61.appspot.com',
    iosBundleId: 'com.example.jejom',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDQW8Eda18PoRmwrMv3SkndxLvtY8qhW-Y',
    appId: '1:254944558379:web:ba008b6ad884aaf83fd96e',
    messagingSenderId: '254944558379',
    projectId: 'jejom-d5d61',
    authDomain: 'jejom-d5d61.firebaseapp.com',
    storageBucket: 'jejom-d5d61.appspot.com',
    measurementId: 'G-GS4RP8KZX3',
  );
}
